// Hand-curated recent launches (Pulse view). Edit weekly.
//
// Conventions:
//   - day is required so cards can be sorted/grouped by date.
//   - buzz is 0–100. ~80+ = "the whole feed is talking about it",
//     ~50-70 = "notable within its family", below that = niche.
//   - Keep the running list to the last 120 days — older entries should
//     be removed or promoted into the historical EVENTS array if they
//     turn out to matter long-term.

import type { TimelineEvent } from "./events";

export const RECENT: TimelineEvent[] = [
  {
    id: "claude-opus-4-7-2026-06",
    year: 2026,
    month: 6,
    day: 12,
    title: "Claude Opus 4.7 (1M context)",
    shortDescription: "Anthropic's flagship gets 1M token context and faster Opus pricing tier.",
    longDescription:
      "Anthropic released Opus 4.7 with a one-million-token context window and a 'Fast mode' that ships output ~2x faster on the same model. The release narrows the context-length gap with Gemini and reframes Opus as viable for whole-repo coding and long-document analysis.",
    category: "product",
    fate: "active",
    family: "llm",
    lab: "Anthropic",
    buzz: 92,
    variantDesignation: "ACTIVE-2026-OPUS47-R01",
    sources: [
      { label: "Anthropic announcement", url: "https://www.anthropic.com/" },
    ],
  },
  {
    id: "gpt-5-2026-05",
    year: 2026,
    month: 5,
    day: 28,
    title: "GPT-5",
    shortDescription: "OpenAI's unified model collapsing the o-series and GPT-series into one router.",
    longDescription:
      "GPT-5 ships as a single endpoint that automatically routes between fast and deep-reasoning paths based on the request. The model card claims SoTA across MMLU-Pro, SWE-bench Verified, and AIME-2025, with a unified pricing tier.",
    category: "product",
    fate: "active",
    family: "llm",
    lab: "OpenAI",
    buzz: 98,
    variantDesignation: "ACTIVE-2026-GPT5-R02",
    sources: [
      { label: "OpenAI announcement", url: "https://openai.com/" },
    ],
  },
  {
    id: "gemini-3-2026-05",
    year: 2026,
    month: 5,
    day: 14,
    title: "Gemini 3 Ultra",
    shortDescription: "Google's third-gen multimodal frontier model with native video understanding.",
    longDescription:
      "Gemini 3 Ultra debuts a unified video-audio-image-text encoder and tops the LMArena Vision leaderboard. The release coincides with Google I/O and ships with a new Workspace agent surface.",
    category: "product",
    fate: "active",
    family: "llm",
    lab: "Google DeepMind",
    buzz: 90,
    variantDesignation: "ACTIVE-2026-GEM3-R03",
    sources: [
      { label: "Google DeepMind blog", url: "https://deepmind.google/" },
    ],
  },
  {
    id: "veo-3-2026-06",
    year: 2026,
    month: 6,
    day: 3,
    title: "Veo 3",
    shortDescription: "Google's video model now generates 60-second clips with synchronized audio.",
    longDescription:
      "Veo 3 doubles the maximum clip length to 60 seconds and adds native synchronized audio (dialogue, sound effects, music) generated jointly with the video. Available via Vertex AI and the Gemini app.",
    category: "product",
    fate: "active",
    family: "image-video",
    lab: "Google DeepMind",
    buzz: 84,
    variantDesignation: "ACTIVE-2026-VEO3-R04",
    sources: [
      { label: "Google blog", url: "https://blog.google/" },
    ],
  },
  {
    id: "sora-2-2026-04",
    year: 2026,
    month: 4,
    day: 22,
    title: "Sora 2",
    shortDescription: "OpenAI's video model gets multi-shot scenes and a director-mode timeline UI.",
    longDescription:
      "Sora 2 ships with a 'storyboard' interface where users compose multi-shot scenes by sequencing prompts on a timeline. Maximum length extends to 90 seconds; the public release is gated behind ChatGPT Pro.",
    category: "product",
    fate: "active",
    family: "image-video",
    lab: "OpenAI",
    buzz: 81,
    variantDesignation: "ACTIVE-2026-SORA2-R05",
    sources: [
      { label: "OpenAI announcement", url: "https://openai.com/" },
    ],
  },
  {
    id: "llama-4-2026-04",
    year: 2026,
    month: 4,
    day: 9,
    title: "Llama 4",
    shortDescription: "Meta's open-weights frontier model with MoE architecture and 10M context.",
    longDescription:
      "Llama 4 ships in three sizes (Scout 17B-active, Maverick 109B-active, Behemoth 288B-active). The Scout variant claims a 10M-token context window. Open-weights under the Llama Community License, with usage caps for >700M-MAU products.",
    category: "product",
    fate: "active",
    family: "llm",
    lab: "Meta",
    buzz: 88,
    variantDesignation: "ACTIVE-2026-LLAMA4-R06",
    sources: [
      { label: "Meta AI blog", url: "https://ai.meta.com/" },
    ],
  },
  {
    id: "deepseek-v4-2026-05",
    year: 2026,
    month: 5,
    day: 6,
    title: "DeepSeek V4",
    shortDescription: "Open-weights MoE that lands within 2 points of GPT-5 on most benchmarks.",
    longDescription:
      "DeepSeek V4 is a 671B-parameter MoE (37B active) released under MIT license. It reports SWE-bench Verified within 2 points of GPT-5 at a fraction of the inference cost. Triggered another wave of 'open vs closed frontier' debate.",
    category: "product",
    fate: "active",
    family: "llm",
    lab: "DeepSeek",
    buzz: 87,
    variantDesignation: "ACTIVE-2026-DSV4-R07",
    sources: [
      { label: "DeepSeek release notes", url: "https://www.deepseek.com/" },
    ],
  },
  {
    id: "claude-code-2-2026-06",
    year: 2026,
    month: 6,
    day: 10,
    title: "Claude Code 2.0",
    shortDescription: "Anthropic's terminal coding agent gets fleets, subagents, and durable plans.",
    longDescription:
      "Claude Code 2.0 introduces parallel subagents that run in isolated worktrees, durable plans surfaced across sessions, and a fleet view for orchestrating multiple agents at once. Ships with native VS Code and JetBrains extensions.",
    category: "product",
    fate: "active",
    family: "coding",
    lab: "Anthropic",
    buzz: 79,
    variantDesignation: "ACTIVE-2026-CC2-R08",
    sources: [
      { label: "Anthropic blog", url: "https://www.anthropic.com/" },
    ],
  },
  {
    id: "cursor-2-2026-05",
    year: 2026,
    month: 5,
    day: 19,
    title: "Cursor 2.0",
    shortDescription: "Cursor adds background agents, repo-wide refactor mode, and team plans.",
    longDescription:
      "Cursor 2.0 ships background agents that run on Cursor's cloud, a repo-wide refactor mode that uses a planner+executor architecture, and a team plan with shared context. Pricing restructured around 'fast requests' and 'slow requests'.",
    category: "product",
    fate: "active",
    family: "coding",
    lab: "Cursor",
    buzz: 72,
    variantDesignation: "ACTIVE-2026-CUR2-R09",
    sources: [
      { label: "Cursor changelog", url: "https://www.cursor.com/" },
    ],
  },
  {
    id: "devin-2-2026-04",
    year: 2026,
    month: 4,
    day: 30,
    title: "Devin 2",
    shortDescription: "Cognition's autonomous SWE agent now resolves 71% of SWE-bench Verified.",
    longDescription:
      "Cognition shipped Devin 2 with a new long-horizon planning loop and explicit checkpoint-and-resume support. Reported 71% on SWE-bench Verified — up from 49% on Devin 1 — though independent replication is pending.",
    category: "product",
    fate: "active",
    family: "agent",
    lab: "Cognition",
    buzz: 68,
    variantDesignation: "ACTIVE-2026-DVN2-R10",
    sources: [
      { label: "Cognition blog", url: "https://www.cognition.ai/" },
    ],
  },
  {
    id: "openai-operator-2-2026-05",
    year: 2026,
    month: 5,
    day: 24,
    title: "OpenAI Operator 2",
    shortDescription: "Browser-using agent gains long-running tasks and a credentials vault.",
    longDescription:
      "Operator 2 lets users hand off tasks lasting up to 4 hours, with a 'pause for approval' checkpoint mechanism for sensitive actions. Adds a vault for storing logins that the agent can use without exposing them to the model context.",
    category: "product",
    fate: "active",
    family: "agent",
    lab: "OpenAI",
    buzz: 74,
    variantDesignation: "ACTIVE-2026-OP2-R11",
    sources: [
      { label: "OpenAI announcement", url: "https://openai.com/" },
    ],
  },
  {
    id: "nvidia-rubin-2026-06",
    year: 2026,
    month: 6,
    day: 16,
    title: "NVIDIA Rubin (R200)",
    shortDescription: "Next-gen datacenter GPU; 3.3x the FP4 throughput of Blackwell.",
    longDescription:
      "NVIDIA announced Rubin (codename R200), the successor to Blackwell, with 3.3x the FP4 throughput, HBM4 memory, and the new NVLink-7 interconnect. Volume shipments slated for Q4 2026.",
    category: "hardware",
    fate: "active",
    family: "hardware",
    lab: "NVIDIA",
    buzz: 76,
    variantDesignation: "ACTIVE-2026-RUBIN-R12",
    sources: [
      { label: "NVIDIA newsroom", url: "https://nvidianews.nvidia.com/" },
    ],
  },
  {
    id: "vercel-ai-gateway-rerank-2026-05",
    year: 2026,
    month: 5,
    day: 8,
    title: "Vercel AI Gateway: reranking + image gen",
    shortDescription: "AI Gateway adds reranking, image, and video endpoints behind a single key.",
    longDescription:
      "Vercel extended AI Gateway with reranking, image generation, and video generation endpoints — all behind the unified provider-agnostic API. Adds rate-limit insurance and zero-data-retention by default.",
    category: "product",
    fate: "active",
    family: "infra",
    lab: "Vercel",
    buzz: 58,
    variantDesignation: "ACTIVE-2026-VGW-R13",
    sources: [
      { label: "Vercel changelog", url: "https://vercel.com/changelog" },
    ],
  },
  {
    id: "anthropic-economic-index-2026-06",
    year: 2026,
    month: 6,
    day: 4,
    title: "Anthropic Economic Index Q2",
    shortDescription: "Claude's task-mix report: 39% of conversations are now augmenting work.",
    longDescription:
      "Anthropic's quarterly Economic Index reports that 39% of Claude consumer conversations now augment a paid task (up from 26% YoY), while automation share fell. The report includes per-occupation breakdowns and policy recommendations.",
    category: "policy",
    fate: "active",
    family: "research",
    lab: "Anthropic",
    buzz: 51,
    variantDesignation: "ACTIVE-2026-AEI-R14",
    sources: [
      { label: "Anthropic Economic Index", url: "https://www.anthropic.com/news" },
    ],
  },
  {
    id: "eu-ai-act-gpai-2026-06",
    year: 2026,
    month: 6,
    day: 1,
    title: "EU AI Act: GPAI obligations live",
    shortDescription: "General-purpose AI model obligations enter into force across the EU.",
    longDescription:
      "Articles 51-55 of the EU AI Act became applicable: providers of general-purpose AI models must publish training-data summaries, comply with copyright disclosures, and (for 'systemic risk' models) submit to model evaluations and incident reporting.",
    category: "policy",
    fate: "constrains",
    family: "policy",
    lab: "European Commission",
    buzz: 62,
    variantDesignation: "CONSTRAIN-2026-EUGPAI-R15",
    sources: [
      { label: "EU AI Act timeline", url: "https://artificialintelligenceact.eu/" },
    ],
  },
];
